export const actionTypes = {
  LOGIN: 'LOGIN',
  DELETE_EXPENSE: 'DELETE_EXPENSE',
  ENABLE_EDIT_EXPENSE: 'ENABLE_EDIT_EXPENSE',
  EDIT_EXPENSE: 'EDIT_EXPENSE',
  FETCH_CURRENCY_REQUEST: 'FETCH_CURRENCY_REQUEST',
  FETCH_CURRENCY_SUCCESS: 'FETCH_CURRENCY_SUCCESS',
  FETCH_CURRENCY_SUCCESS_EXPENSE: 'FETCH_CURRENCY_SUCCESS_EXPENSE',
  FETCH_CURRENCY_FAILURE: 'FETCH_CURRENCY_FAILURE',
};
